theme = "hugo-PaperMod"
relativeURLs = true
baseURL = "https://brownstein.co/"
title = "Cody Brownstein's Website"
author = "Cody Brownstein"
copyright = "© 2020-2021 Cody Brownstein, unless otherwise indicated. All rights reserved."
paginate = 7
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params]
  author = "Cody Brownstein"
  showShareButtons = true

  [params.homeInfoParams]
    Title = "Welcome to Cody Brownstein's Website!"
    Content = """I created this website to showcase the content I've written \
    for clients on [different topics](/tags). Check out the \
    [About page](/about) for more information about this website."""
